version: '3.8'

services:
  frontend:
    image: tkddmskr/odegano-frontend:latest
    container_name: odegano-frontend
    restart: unless-stopped
    networks:
      - odegano-network
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.odegano.kro.kr
    volumes:
      - frontend-static:/usr/share/nginx/html

  
  nginx:
    image: nginx:alpine
    container_name: odegano-nginx
    restart: unless-stopped
    networks:
      - odegano-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./ssl:/etc/nginx/ssl:ro
      - frontend-static:/usr/share/nginx/html:ro
    depends_on:
      - frontend

networks:
  odegano-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400

volumes:
  postgres_data:
  frontend-static: